---

- name: "Deploy Nginx HTTP(s) files"
  synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ nginx_conf_path }}"

- name: "Run the local Nginx container"
  docker_container:
    name: nginx
    hostname: "{{ ansible_hostname }}"
    state: started
    pull: yes
    restart: yes
    recreate: yes
    restart_policy: "unless-stopped"
    image: "{{ docker_nginx_image }}"
    volumes:
      - "{{ nginx_conf_path }}:/etc/nginx/conf.d"
      - "{{ nginx_data_path }}:/var/www"
    exposed_ports:
      - "{{ nginx_http_port }}"
      - "{{ nginx_https_port }}"
    published_ports:
      - "{{ nginx_http_port }}:{{ nginx_published_http_port }}"
      - "{{ nginx_https_port }}:{{ nginx_published_https_port }}"
  tags: nginx,run
