---

- name: "Create all required directories"
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ installation_prefix }}"
    - "{{ volumes_prefix_nginx }}"
    - "{{ nginx_conf_path }}"
    - "{{ nginx_data_path }}"
  tags: nginx,mkdir

- name: "Deploy Nginx HTTP(s) files"
  synchronize:
    src: "{{ nginx_conf_src }}"
    dest: "{{ nginx_conf_path }}"
  tags: nginx,conf

- name: "Run the local Nginx container"
  docker_container:
    name: "{{ S }}"
    hostname: "{{ ansible_hostname }}"
    state: started
    pull: yes
    restart: yes
    recreate: yes
    restart_policy: "unless-stopped"
    image: "{{ docker_nginx_image }}"
    volumes:
      - "{{ nginx_conf_path }}:/etc/nginx/conf.d"
      - "{{ nginx_data_path }}:/var/www"
    exposed_ports:
      - "{{ nginx_http_port }}"
      - "{{ nginx_https_port }}"
    published_ports:
      - "{{ nginx_http_published_port }}:{{ nginx_http_port }}"
      - "{{ nginx_https_published_port }}:{{ nginx_https_port }}"
  tags: nginx,run
