---

- name: Test HTTP port
  wait_for:
    port: "{{ item }}"
    host: "{{ ansible_default_ipv4.address }}"
    timeout: 120
    msg: "Check HTTP(S) ports"
  with_items:
    - "{{ nginx_http_published_port }}"
#    - "{{ nginx_https_published_port }}"
  tags: nginx,test
